### PR TITLE
Emit CallEvent.declined when callee is busy. (Twilio Error 31486)

### LINKED ISSUE #124: Should send 'Call Declined' event on "Call Error: 31486, Busy Here".
At the moment, `CallEvent.log` is received on the caller side when a callee declines the call. `Call Error: 31486, Busy Here` is logged but not sent as a `CallEvent.declined` event. (answerOnBridge is enabled.)

This can be easily achieved by updating `_parseCallEvent` method in `TwilioVoice` class.

**Current code:**

```dart
...
 else if (state.startsWith("LOG|")) {
      List<String> tokens = state.split('|');
      print(tokens[1]);

      // source: https://www.twilio.com/docs/api/errors/31603
      // The callee does not wish to participate in the call.
      if(tokens[1].contains("31603")) {
        return CallEvent.declined;
      } else if(tokens.toString().toLowerCase().contains("call rejected")) {
        // Android call reject from string: "LOG|Call Rejected"
        return CallEvent.declined;
      } else if(tokens.toString().toLowerCase().contains("rejecting call")) {
        // iOS call reject froms tring: "LOG|provider:performEndCallAction: rejecting call"
        return CallEvent.declined;
      }
      return CallEvent.log;
    }
 ...
```

**Solution:**
Added check for Error Code: 31486

```dart
...
 else if (state.startsWith("LOG|")) {
      List<String> tokens = state.split('|');
      print(tokens[1]);

      // source: https://www.twilio.com/docs/api/errors/31603
      // The callee does not wish to participate in the call.
      if(tokens[1].contains("31603") || tokens[1].contains("31486")) {   // Added check for Error Code: 31486 here
        return CallEvent.declined;
      } else if(tokens.toString().toLowerCase().contains("call rejected")) {
        // Android call reject from string: "LOG|Call Rejected"
        return CallEvent.declined;
      } else if(tokens.toString().toLowerCase().contains("rejecting call")) {
        // iOS call reject froms tring: "LOG|provider:performEndCallAction: rejecting call"
        return CallEvent.declined;
      }
      return CallEvent.log;
    }
 ...
```

### PR DESCRIPTION
**Pull request by agent515**
Fix #124

### CODE REVIEW

**Review by cybex-dev — CHANGES_REQUESTED** [review]
Please update with current master.

File: lib/twilio_voice.dart [hunk 1]
```diff
@@ -259,7 +262,8 @@ class Call {
 
   /// Gets the active call's SID. This will be null until the first Ringing event occurs
   Future<String?> getSid() {
-    return _channel.invokeMethod<String?>('call-sid', <String, dynamic>{}).then<String?>((String? value) => value);
+    return _channel.invokeMethod<String?>('call-sid',
```
Comment (cybex-dev) [inline lib/twilio_voice.dart]: @agent515 lets get rid of these changes please, i.e. only the error code changes.

Comment (agent515) [reply lib/twilio_voice.dart]: @cybex-dev I understand what you're saying. But I think it's linter that is doing these changes upon saving file. I'm not sure about how to prevent this.

**Review by cybex-dev — APPROVED** [review]

File: lib/twilio_voice.dart (hunk 1 above)
Comment (cybex-dev) [reply lib/twilio_voice.dart]: No worries, thanks
