### PR TITLE
Macos: Fix mic permission access

### LINKED ISSUE #264: Can't place a call on macOS
### Issue Summary

The call doesn't start, mac on M3 chip

Is it working for you?

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
1. Updated twilio sdk to latest one 
2. Fixed permission request for macos 12 and higher
3. Most important: Fixed Doc (!)

Fixes https://github.com/cybex-dev/twilio_voice/issues/264

### CODE REVIEW

File: macos/Classes/TwilioVoicePlugin.swift [hunk 1]
```diff
@@ -1142,9 +1142,9 @@ public class TwilioVoicePlugin: NSObject, FlutterPlugin, FlutterStreamHandler, T
         if let category = NotificationCategory(rawValue: notification.request.content.categoryIdentifier) {
             switch category {
             case .incoming:
-                completionHandler([.alert, .banner, .sound])
```
Comment (AndreiMisiukevich) [inline macos/Classes/TwilioVoicePlugin.swift:1145]: alert is deprecated starting macos 11.0

**Comment by AndreiMisiukevich** [comment]
could you please take a look?

**Comment by AndreiMisiukevich** [comment]
Oh, I see why SDK hasn't been updated... new updated breaks "status" event handling

This is because of outdated sdk was used

**Review by cybex-dev — APPROVED** [review]
Absolutely amazing PR, thank you very much!
